### ISSUE TITLE
Odoo11: Account Payment Advance is not installable

### ISSUE THREAD

**Issue by ccandito** [KonosCL/addons-konos#3]
Please find below the system log:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo11/odoo.11-dev/odoo/odoo/models.py", line 967, in _validate_fields
    check(self)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/addons/base/ir/ir_ui_view.py", line 338, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/addons/base/ir/ir_ui_view.py", line 998, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
    raise ValueError(message)
ValueError: Field `advance_ok` does not exist

Error context:
View `account.payment.advance.view`
[view_id: 1288, xml_id: n/a, model: account.payment, parent_id: 442]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo11/odoo.11-dev/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/home/odoo11/odoo.11-dev/odoo/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo11/odoo.11-dev/odoo/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo11/odoo.11-dev/odoo/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nField `advance_ok` does not exist\n\nError context:\nView `account.payment.advance.view`\n[view_id: 1288, xml_id: n/a, model: account.payment, parent_id: 442]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo11/odoo.11-dev/odoo/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo11/odoo.11-dev/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo11/odoo.11-dev/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo11/odoo.11-dev/odoo/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo11/odoo.11-dev/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/home/odoo11/odoo.11-dev/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/odoo11/odoo.11-dev/odoo/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/home/odoo11/odoo.11-dev/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/home/odoo11/odoo.11-dev/odoo/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo11/odoo.11-dev/odoo/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo11/odoo.11-dev/odoo/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/home/odoo11/odoo.11-dev/odoo/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Field `advance_ok` does not exist

Error context:
View `account.payment.advance.view`
[view_id: 1288, xml_id: n/a, model: account.payment, parent_id: 442]
None" while parsing /home/odoo11/odoo.11-dev/odoo/addons/account_payment_advance/view/account_payment_advance.xml:4, near
<record model="ir.ui.view" id="account_payment_advance_view">
                <field name="name">account.payment.advance.view</field>
                <field name="model">account.payment</field>
                <field name="inherit_id" ref="account.view_account_payment_form"/>
                <field name="arch" type="xml">
                    <field name="communication" position="after">
                        <field name="advance_ok"/>
                        <field name="advance_account_id" domain="[('reconcile', '=', True)]" attrs="{'invisible':[('advance_ok', '!=', True)]}"/>
                    </field>
                </field>
        </record>

**Comment by nelsonramirezs** [comment]
Thank you, will update ASAP
