### ISSUE TITLE
Error al instalar el modulo Chilean Payroll & Human Resources

### ISSUE THREAD

**Issue by patsotoe** [KonosCL/addons-konos#70]
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/models.py", line 1126, in _validate_fields
    check(self)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 1098, in postprocess_and_fields
    self.raise_view_error(_('Model not found: %(model)s') % dict(model=model), view_id)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 568, in raise_view_error
    raise ValueError(message)
ValueError: Modelo no encontrado: hr.indicadores

Contexto del error:
Vista `hr.indicadores.view`
[view_id: 1548, xml_id: n/a, model: hr.indicadores, parent_id: n/a]

**Comment by dansanti** [comment]
hola,esto es normalmente porque no han reiniciado el servicio odoo o quedó mal cargo luego del reinicio

**Comment by patsotoe** [comment]
gracias reinicie el servicio y funciono de maravillas.
